### ISSUE TITLE
Name change and version

### ISSUE THREAD

**Issue by millette** [solidjs/solid-meta#15]
I hope it's ok to change my dependencies (router and meta) to namespaced ones. I just notice an oddity with the meta versions:

Both were updated the same day but one is 0.28.0 and the latter 0.28.1:

* https://www.npmjs.com/package/@solidjs/meta
* https://www.npmjs.com/package/solid-meta

Just thought I'd mention it.

**Comment by ryansolid** [comment]
Yeah do so.. 0.28.1 was so I could get the deprecation message up.
