### ISSUE TITLE
v0.28.5 release has dist from v0.28.4 

### ISSUE THREAD

**Issue by katywings** [solidjs/solid-meta#32]
Quick reminder regarding the v0.28.5 npm release of this package: The dist doesn't include the fix from 5917a1a7e7668cf6906379f97276056d985a7234 . This can be seen via https://unpkg.com/@solidjs/meta@0.28.5/dist/index.js.

Thank you in advance 😊!

**Comment by ryansolid** [comment]
Ok fixed in 0.28.6
