### ISSUE TITLE
Using multiple values from routeData object in Title appears to insert extra commas

### ISSUE THREAD

**Issue by rpivo** [solidjs/solid-meta#37]
Reproduced issue here:
https://stackblitz.com/edit/solidjs-templates-pblvuq?file=src%2Froutes%2Ftest%2F%5Bid%5D.tsx

Start with `npm run dev`, then navigate to route **/test/1**.

The title should read `abel bernice charlie`, but instead it reads `abel, ,bernice, ,charlie`.

I am not sure that this has anything to do with using `routeData` at all -- this is just how I am able to reproduce the issue.

**Comment by iacore** [comment]
it's treated as a list. 

workaround: concatenate the strings yourself

**Comment by JakkuSakura** [comment]
Isn't the list be concatenated with no spacing, like any other children in JSX components

**Comment by iacore** [comment]
> Isn't the list be concatenated with no spacing, like any other children in JSX components

`[1, 2].toString()`
