### ISSUE TITLE
renderToString failing

### ISSUE THREAD

**Issue by snargle007** [solidjs/solid-meta#4]
Hi,

Using the example code:

  const tags = []; // mutated during render so you can include in server-rendered template later
  const app = renderToString(
    <MetaProvider tags={tags}>
      <App />
    </MetaProvider>
  );

I get an error:
server.js:14
    <MetaProvider tags={tags}>
    ^

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by ryansolid** [comment]
Can I get more context? Bundler? Rest of the file? The example in the README is expected to be in the context of a req handler from something like Express. This error suggests a syntax error but I feel I'm missing something.

**Comment by snargle007** [comment]
Hey - sorry about no context!

**Comment by snargle007** [comment]
Not sure how I "closed" the issue :(

**Comment by ryansolid** [comment]
Are you running rollup on the server code as well. I think it might be choking on the JSX and doesn't know how to deal with it. You probably need to build the serverside as well. There are a few extra things in here, but this config might be helpful as reference: https://github.com/solidjs/solid/blob/main/packages/solid-ssr/examples/ssr/rollup.config.js.

The `ssr` folder in that example is essentially what you are looking at I think.

**Comment by snargle007** [comment]
I updated rollup.config.js to below (it then requires import json from '@rollup/plugin-json'; but then I get a circular dependencies). I'll check around some more. I guess this really isn't an "Issue", it's more of a build process problem on my end,

import { resolve, nodeResolve } from "@rollup/plugin-node-resolve";
import babel from "@rollup/plugin-babel";
import del from "rollup-plugin-delete";
import common from "@rollup/plugin-commonjs";
import copy from "rollup-plugin-copy";
import json from '@rollup/plugin-json';

export default [
  {
    input: "src/server.js",
    output: [
      {
        dir: "static/server.js",
        format: "cjs"
      }
    ],
    external: ["solid-js", "solid-js/web", "path", "express", "stream"],
    plugins: [
      del({
        targets: ["public/*.js", "!public/index.html"],
        watch: true
      }),
      nodeResolve({ preferBuiltins: true, exportConditions: ["solid", "node"] }),
      babel({
        babelHelpers: "bundled",
        presets: [["solid", { generate: "ssr", hydratable: true }]],
      }),
      common(),
      json()
    ],
    preserveEntrySignatures: false
  },
  {
    input: "src/index.js",
    output: [
      {
        dir: "public",
        format: "esm"
      }
    ],
    preserveEntrySignatures: false,
    plugins: [
      nodeResolve({ exportConditions: ["solid"] }),
      babel({
        babelHelpers: "bundled",
        presets: [["solid", { generate: "dom", hydratable: true }]],
        exclude: "node_modules/**",
        plugins: ["@babel/syntax-dynamic-import", "@babel/plugin-proposal-optional-chaining"]
      }),
      common(),
      copy({
        targets: [
          {
            src: ["static/*"],
            dest: "public"
          }
        ]
      })
    ]
  }
];


(!) Circular dependencies
../node_modules/@grpc/grpc-js/build/src/channel.js -> ../node_modules/@grpc/grpc-js/build/src/subchannel-pool.js -> ../node_modules/@grpc/grpc-js/build/src/subchannel.js -> ../node_modules/@grpc/grpc-js/build/src/channelz.js -> ../node_modules/@grpc/grpc-js/build/src/make-client.js -> ../node_modules/@grpc/grpc-js/build/src/client.js -> ../node_modules/@grpc/grpc-js/build/src/channel.js
../node_modules/@grpc/grpc-js/build/src/channel.js -> ../node_modules/@grpc/grpc-js/build/src/subchannel-pool.js -> ../node_modules/@grpc/grpc-js/build/src/subchannel.js -> ../node_modules/@grpc/grpc-js/build/src/channelz.js -> ../node_modules/@grpc/grpc-js/build/src/make-client.js -> ../node_modules/@grpc/grpc-js/build/src/client.js -> /home/jim/firebase/node_modules/@grpc/grpc-js/build/src/channel.js?commonjs-proxy -> ../node_modules/@grpc/grpc-js/build/src/channel.js
../node_modules/protobufjs/src/util/minimal.js -> ../node_modules/protobufjs/src/util/longbits.js -> ../node_modules/protobufjs/src/util/minimal.js

**Comment by ryansolid** [comment]
Sometimes these are just warnings and it will still work. Sometimes you need to change code organization. Does it complete build and can it run? You could always set @grpc/grpc-js as an external dependency on the server and not pull it in. `external: ["@grpc/grpc-js"]` or something like that.

**Comment by snargle007** [comment]
I finally gave up and am using the solid-ssr package and trying to add meta tag generation to that. I may not be good enough at JS to get that working. We'll see. If I do, that might be another good starter app - SSR with dynamic Meta Tags.

**Comment by ryansolid** [comment]
You might be interested in this starter template: https://github.com/amoutonbrady/vite-ssr-solid

**Comment by snargle007** [comment]
Hmm - I'll try that before going to far :)

**Comment by snargle007** [comment]
That worked for the meta tags!, but now trying to use router-app and meta together in Browser.tsx

import type { Component } from "solid-js";
import { MetaProvider } from "solid-meta";
import { App } from "./App";

import { useRoutes, Router, Route } from "solid-app-router";
import { lazy } from "solid-js";

const routes = [{
	path: "/comments",
	component: lazy(() => import("./comment"))
}];

const Routes = useRoutes(routes);

const Browser: Component = () => {
  return (
    <Router>
      <MetaProvider>
        <App />
      </MetaProvider>
    </Router>
  );
};

export default Browser;


and the comment.tsx:

import { Component, createSignal } from "solid-js";

const Comment: Component<{}> = (props) => {
  const [open, setOpen] = createSignal(true);

  return (
    <div>
      Comments!

    </div>
  );
};

export default Comment;

**Comment by snargle007** [comment]
Worked for the meta tags - Now trying to get routing to a page other than / with new meta tags (So far not working).

Browser.tsx:

import type { Component } from "solid-js";
import { MetaProvider } from "solid-meta";
import { App } from "./App";
import { Router } from "solid-app-router";

const Browser: Component = () => {
  return (
    <Router>
      <MetaProvider>
        <App />
      </MetaProvider>
    </Router>
  );
};

export default Browser;


import { createSignal, Switch, Match } from "solid-js";
import { Title, Link, Meta } from "solid-meta";
import favicon from "../static/favicon.svg?url";
import { useLocation, useRoutes, NavLink } from "solid-app-router";
import Comment from "./comment";


import { lazy } from "solid-js";

const routes = [{
	path: "/comments",
	component: lazy(() => import("./comment"))
}];

export const App = () => {
	const MyRoutes = useRoutes(routes);	
	const [count, setCount] = createSignal(0);

	const counts = (Count: () => number): string => {
		const count = Count();
		return `${count} time${count === 1 ? "" : "s"}`;
	};

    const metaKeywords = "sdsdsd";
    const metaDescription = "sdsdsd";

	const location = useLocation();

	return (
		<>
			<Title>Solid.js & Vite - SSR</Title>
			<Link rel="shortcut icon" type="image/svg+xml" href={favicon} />
			<Meta name="keywords" content={metaKeywords} />
			<Meta name="description" content={metaDescription} />
			<Switch fallback={<div>Not Found</div>}>
				<Match when={location.pathname === "/"}>
					{location.pathname}
					<div>
						<button onClick={() => setCount(count() + 1)}>Click me</button>
						<p> The Button Has been clicked {counts(count)}</p>
					</div>
					<NavLink href="/comment" end>Comment</NavLink>
				</Match>
				<Match when={location.pathname === "/comment"}>
					vcbbdgdghdf
					<Comment />
				</Match>
			</Switch>
			<MyRoutes />
		</>
	);
};

export default App;

location.pathname always is "/"

**Comment by snargle007** [comment]
Worked for the meta tags - Now trying to get routing to a page other than / with new meta tags
I have it working to change meta tags using a router navlink, but not directly deep link in to /comment.
Once I have that figured out I could create a starter ssr app with meta tag replacement :)

**Comment by snargle007** [comment]
Ok - I have it working - routing, dynamic meta tags, deep linking.
Last thing (I think) is CSS
I add:
<Link rel="stylesheet" type="text/css" href={styles} /> in App.tsx
It is copied to /dist/client/ as:
<link rel="stylesheet" href="/assets/index.280796b7.css">
but it gets rendered as:
<link data-sm="" rel="stylesheet" type="text/css" href="export default "/static/styles.css""/>


<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module" src="/@vite/client"></script>
    <meta charset="utf-8" />
    <title data-sm="">Solid.js & Vite - SSR</title>
    <link data-sm="" rel="stylesheet" type="text/css" href="export default "/static/styles.css""/>
    ...
  </head>
  <body>
    <div id="app">...</div>
    <script type="module" src="/src/entry-client.tsx"></script>
  </body>
</html>
