### ISSUE TITLE
New Version Release Required

### ISSUE THREAD

**Issue by dddieon** [solidjs/solid-meta#46]
https://github.com/solidjs/solid-meta/commit/6ed1c1bb8120b489b5f24c782c8b6ce1bc3e3839

I think the runtime error issue that seems to have been fixed in a commit on the main branch.
However, the fix hasn't been reflected in the latest release on npm.

[Fixed PR - Error in solid-meta when navigating solid-start app](https://github.com/solidjs/solid-meta/issues/38)
[Related PR - Proposal: use a key prop to override Meta tags #39
](https://github.com/solidjs/solid-meta/pull/39)

**Comment by ryansolid** [comment]
Yeah released. 0.29.4. Thanks for the nudge.

**Comment by dddieon** [comment]
Cool!
